export const CODE_GROUPS = [
    'Firearm Violations',
    'Confidence Games',
    'Larceny From Motor Vehicle',
    'Towed',
    'Property Related Damage',
    'Missing Person Located',
    'Auto Theft Recovery',
    'INVESTIGATE PERSON',
    'Harbor Related Incidents',
    'Service',
    'Harassment',
    'Landlord / Tenant Disputes',
    'Property Found',
    'HUMAN TRAFFICKING',
    'Vandalism',
    'License Violation',
    'Robbery',
    'License Plate Related Incidents',
    'Counterfeiting',
    'Warrant Arrests',
    'Disorderly Conduct',
    'Motor Vehicle Accident Response',
    'Biological Threat',
    'Embezzlement',
    'Ballistics',
    'Prisoner Related Incidents',
    'Other Burglary',
    'Verbal Disputes',
    'Auto Theft',
    'Medical Assistance',
    'Restraining Order Violations',
    'Manslaughter',
    'Larceny',
    'Evading Fare',
    'Aircraft',
    'Drug Violation',
    'Bomb Hoax',
    'Fire Related Reports',
    'HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE',
    'Criminal Harassment',
    'HOME INVASION',
    'Search Warrants',
    'Homicide',
    'Fraud',
    'Prostitution',
    'Explosives',
    'Residential Burglary',
    'Operating Under the Influence',
    'Recovered Stolen Property',
    'Other',
    'Liquor Violation',
    'Commercial Burglary',
    'Gambling',
    'Investigate Person',
    'Aggravated Assault',
    'Simple Assault',
    'Property Lost',
    'Phone Call Complaints',
    'Missing Person Reported',
    'Burglary - No Property Taken',
    'Arson',
    'Firearm Discovery',
    'Assembly or Gathering Violations',
    'Police Service Incidents',
    'Violations',
    'Offenses Against Child / Family',
    'Investigate Property'
];
